import streamlit as st
import plotly.graph_objects as go

from predict import predict_image
from tumor_info import tumor_info

# -----------------------------------
# Page Configuration
# -----------------------------------

st.set_page_config(
    page_title="Brain Tumor Classification",
    page_icon="🧠",
    layout="wide"
)

# -----------------------------------
# Title
# -----------------------------------

st.title("🧠 Brain Tumor Classification using Deep Learning")

st.markdown("""
Upload a **Brain MRI image** and the AI model will predict the tumor type.

> ⚠ **Educational Project Only**
> This application is intended for educational purposes and should not be used as a medical diagnosis.
""")

st.divider()

# -----------------------------------
# Upload Image
# -----------------------------------

uploaded_file = st.file_uploader(
    "Upload MRI Image",
    type=["jpg", "jpeg", "png"]
)

# -----------------------------------
# Prediction
# -----------------------------------

if uploaded_file is not None:

    image, predicted_class, confidence, probabilities = predict_image(uploaded_file)

    col1, col2 = st.columns([1, 1])

    # -----------------------------
    # Left Column
    # -----------------------------

    with col1:

        st.subheader("Uploaded MRI")

        st.image(image, use_container_width=True)

    # -----------------------------
    # Right Column
    # -----------------------------

    with col2:

        st.subheader("Prediction")

        if predicted_class == "No Tumor":
            st.success(f"✅ {predicted_class}")
        else:
            st.error(f"🧠 {predicted_class}")

        st.metric("Confidence", f"{confidence:.2f}%")

    st.divider()

    # -----------------------------------
    # Probability Chart
    # -----------------------------------

    st.subheader("Prediction Probabilities")

    fig = go.Figure(
        go.Bar(
            x=list(probabilities.keys()),
            y=list(probabilities.values())
        )
    )

    fig.update_layout(
        yaxis_title="Probability (%)",
        xaxis_title="Tumor Type",
        height=450
    )

    st.plotly_chart(fig, use_container_width=True)

    st.divider()

    # -----------------------------------
    # Tumor Information
    # -----------------------------------

    info = tumor_info[predicted_class]

    st.subheader("Description")

    st.write(info["description"])

    st.subheader("Symptoms")

    if len(info["symptoms"]) == 0:
        st.write("No symptoms available.")
    else:
        for symptom in info["symptoms"]:
            st.write("•", symptom)

    st.subheader("Treatment")

    for treatment in info["treatment"]:
        st.write("•", treatment)

    st.subheader("Recommended Doctor")

    st.info(info["doctor"])

    st.divider()

    st.warning(
        "This prediction is generated by an AI model and should not be considered a medical diagnosis. "
        "Please consult a qualified neurologist or radiologist."
    )